name: TypeTalk
options:
  bundleIdPrefix: com.typetalk
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.2"

packages:
  HotKey:
    url: https://github.com/soffes/HotKey
    from: 0.2.1

targets:
  TypeTalk:
    type: application
    platform: macOS
    sources:
      - path: App
      - path: Models
      - path: Services
      - path: Views
      - path: Utilities
      - path: Resources/Assets.xcassets
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.typetalk.app
        PRODUCT_NAME: TypeTalk
        MARKETING_VERSION: "0.1.4"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/TypeTalk.entitlements
        SWIFT_VERSION: "5.9"
        SWIFT_STRICT_CONCURRENCY: minimal
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Developer ID Application: Yoichiro Hasebe (25ME8D76FY)"
        DEVELOPMENT_TEAM: 25ME8D76FY
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: HotKey

  TypeTalkTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.typetalk.app.tests
        SWIFT_VERSION: "5.9"
        INFOPLIST_FILE: ""
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Developer ID Application: Yoichiro Hasebe (25ME8D76FY)"
        DEVELOPMENT_TEAM: 25ME8D76FY
    dependencies:
      - target: TypeTalk

schemes:
  TypeTalk:
    build:
      targets:
        TypeTalk: all
        TypeTalkTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - TypeTalkTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
