name: SpeechDock
options:
  bundleIdPrefix: com.speechdock
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.2"
  developmentLanguage: en
  knownRegions: [en, ja]

packages:
  HotKey:
    url: https://github.com/soffes/HotKey
    from: 0.2.1
  FluidAudio:
    url: https://github.com/FluidInference/FluidAudio
    exactVersion: 0.9.1
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.6.0

targets:
  SpeechDock:
    type: application
    platform: macOS
    sources:
      - path: App
      - path: Models
      - path: Services
      - path: Views
      - path: Utilities
      - path: Resources/Assets.xcassets
        buildPhase: resources
      - path: Resources/SpeechDock.sdef
        buildPhase: resources
      - path: Resources/en.lproj
        buildPhase: resources
      - path: Resources/ja.lproj
        buildPhase: resources
      - path: Resources/zh-Hans.lproj
        buildPhase: resources
      - path: Resources/ko.lproj
        buildPhase: resources
      - path: Resources/de.lproj
        buildPhase: resources
      - path: Resources/fr.lproj
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.speechdock.app
        PRODUCT_NAME: SpeechDock
        MARKETING_VERSION: "0.1.27"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/SpeechDock.entitlements
        SWIFT_VERSION: "5.9"
        SWIFT_STRICT_CONCURRENCY: minimal
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Developer ID Application: Yoichiro Hasebe (25ME8D76FY)"
        DEVELOPMENT_TEAM: 25ME8D76FY
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.speechdock.app.dev
          SPEECHDOCK_DISPLAY_NAME: "SpeechDock Dev"
        Release:
          SPEECHDOCK_DISPLAY_NAME: SpeechDock
    dependencies:
      - package: HotKey
      - package: FluidAudio
      - package: Sparkle

  SpeechDockTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.speechdock.app.tests
        SWIFT_VERSION: "5.9"
        INFOPLIST_FILE: ""
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Developer ID Application: Yoichiro Hasebe (25ME8D76FY)"
        DEVELOPMENT_TEAM: 25ME8D76FY
    dependencies:
      - target: SpeechDock

schemes:
  SpeechDock:
    build:
      targets:
        SpeechDock: all
        SpeechDockTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - SpeechDockTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
